from math import degrees
from manim import *
class Linee(Scene):
    def construct(self):
      sr=Tex("Srijan Chakraborty").scale(1.2)
      pr=Tex("Pythagoras Theorem",color=YELLOW).scale(3)
      abc=Tex("$a^2 +b^2 = c^2$").scale(2).shift(DOWN*1.5)
      self.play(FadeIn(pr,abc))
      self.wait(1)
      self.play(FadeOut(pr,abc))
      tri=Polygon(np.array([0,0,0]),np.array([1,0,0]),np.array([0,1.5,0]),color=GREEN).scale(1.5)
      tri1=Polygon(np.array([0,0,0]),np.array([1,0,0]),np.array([0,1.5,0]),color=BLUE).scale(1.5)
      ac=Tex("ac").next_to(tri1).shift(LEFT*0.9).scale(0.8)
      ab=Tex("ab").next_to(tri1).shift(LEFT*2.2,DOWN*0.1).scale(0.8)
      aa=Tex("$a^2$").next_to(tri1).shift(DOWN*1.3,LEFT*1.1).scale(0.8)
      tex1=Tex("On scaling the triangle by 'a'").next_to(tri1).shift(UP*1.6,LEFT*5).scale(0.6)
      ascale=VGroup(tri1,ab,ac,aa,tex1)
      tri2=Polygon(np.array([0,0,0]),np.array([1,0,0]),np.array([0,1.5,0]),color=YELLOW).scale(1.5)
      bc=Tex("bc").next_to(tri1).shift(LEFT*0.9).scale(0.8)
      bb=Tex("$b^2$").next_to(tri1).shift(LEFT*2.2,DOWN*0.1).scale(0.8)
      ba=Tex("ba").next_to(tri1).shift(DOWN*1.3,LEFT*1.1).scale(0.8)
      tex2=Tex("On scaling the triangle by 'b'").next_to(tri2).shift(UP*1.6,LEFT*5).scale(0.4)
      bscale=VGroup(tri2,bb,ba,bc,tex2)

      tri3=Polygon(np.array([0,0,0]),np.array([1,0,0]),np.array([0,1.5,0]),color=GREEN).scale(1.5)
      c=Tex("c").next_to(tri).shift(LEFT*0.9).scale(0.8)
      b=Tex("b").next_to(tri).shift(LEFT*2,DOWN*0.1).scale(0.8)
      a=Tex("a").next_to(tri).shift(DOWN*1.3,LEFT*1.1).scale(0.8)


      self.play(Write(tri),Write(a),Write(b),Write(c))
      self.wait(2)
      self.play(ascale.animate.shift(LEFT*4))
      self.wait(2)
      self.play(bscale.animate.shift(RIGHT*3).scale(1.5))
      self.wait(2)
      tex11=Tex("Figure 1").next_to(tri1).shift(DOWN*2.5,LEFT*2).scale(0.6)
      tex22=Tex("Figure 2").next_to(tri2).shift(DOWN*2.6,LEFT*3).scale(0.6)
      ascale=VGroup(tri1,ab,ac,aa,tex1,tex11)
      bscale=VGroup(tri2,bb,ba,bc,tex2,tex22)
      self.remove(tri,a,b,c,ascale,bscale)
      self.play(ascale.animate.shift(LEFT*0.5))
      self.play(bscale.animate.shift(RIGHT*0.7))
      t1=Tex("Notice that Figure 1 and Figure 2",color=GREEN).scale(0.6).shift(UP*0.3,LEFT*0.1)
      t2=Tex("have the side 'ab' common",color=GREEN).scale(0.6).shift(LEFT*0.1)
      self.play(Write(t1))
      self.play(Write(t2))
      self.wait(3)
      self.remove(t1,t2)
      t1=Tex("Therefore we can rotate and join ",color=GREEN).scale(0.6).shift(UP*0.3,LEFT*0.1)
      t2=Tex("Figures 1 and 2 by the common side 'ab'",color=GREEN).scale(0.6).shift(LEFT*0.1)
      self.play(Write(t1))
      self.play(Write(t2))
      self.wait(3)
      self.remove(t1,t2,ascale,bscale)
      self.play(Write(tri1),Write(tri2))
      self.remove(ascale,bscale,t1,t2)
      self.play(tri1.animate.rotate(180*DEGREES))
      self.play(tri2.animate.rotate((-90)*DEGREES))
      self.play(tri1.animate.shift(RIGHT*3))
      self.play(tri2.animate.shift(LEFT*3.06,UP*0.06))
      t3=Tex("removing the common line 'ab' gives the triangle",color=GREEN).shift(UP*2.8)
      self.play(Write(t3))
      trix=Polygon(np.array([0,0,0]),np.array([-1,1.5,0]),np.array([2.25,1.5,0]),color=YELLOW).scale(1.5)
      self.remove(tri1,tri2)
      self.play(Write(trix))
      left=Tex("ac").shift(LEFT*1.3,UP*0.7).scale(0.6)
      right=Tex("bc").shift(RIGHT*1.5,UP*0.6).scale(0.6)
      up=Tex("$a^2+b^2$").shift(RIGHT*0.3,UP*2.1).scale(0.6)
      self.play(Write(left),Write(right),Write(up))
      self.wait(2)
      self.remove(t3,left,right,up)
      t3=Tex("scaling by '$(1/c)$'",color=GREEN).shift(UP*2.7).scale(0.6)
      self.play(Write(t3))
      #trix.scale(0.6)
      left=Tex("a").shift(LEFT*0.6,UP*0.7).scale(0.6)
      right=Tex("b").shift(RIGHT*1.1,UP*0.6).scale(0.6)
      up=Tex("$(a^2+b^2)/c$").shift(RIGHT*0.3,UP*1.7).scale(0.6)
      self.play(trix.animate.scale(0.6))
      
      self.play(Write(left),Write(right),Write(up))
      self.wait(1.5)

      self.remove(t3)
      t3=Tex("Congruent to right triangle with sides a,b,c",color=GREEN).shift(LEFT*4,DOWN*1).scale(0.6)
      self.play(Write(t3))
      triy=Polygon(np.array([0,0,0]),np.array([-1,1.5,0]),np.array([2.25,1.5,0]),color=YELLOW).scale(0.9)
      self.play(triy.animate.shift(DOWN*2))
      c=Tex("c").next_to(triy).shift(LEFT*2,UP*0.8).scale(0.6)
      b=Tex("b").next_to(triy).shift(LEFT*1.3,DOWN*0.2).scale(0.6)
      a=Tex("a").next_to(triy).shift(LEFT*2.9,DOWN*0.2).scale(0.6)
      self.play(Write(a),Write(b),Write(c))
      self.wait(1)
      self.remove(t3)
      vgp=VGroup(a,b,c,triy)
      t3=Tex("Equating the length of the hypotenuse :",color=GREEN).shift(LEFT*3.8).scale(0.6)
      t4=Tex("$(a^2+b^2)/c = c$",color=GREEN).shift(LEFT*3.5,DOWN*0.5).scale(0.7)
      t5=Tex("$a^2+b^2=c^2$",color=GREEN).shift(LEFT*3.5,DOWN*1).scale(0.7)
      self.play(Write(t3))
      self.wait(1)
      self.play(Write(t4))
      self.wait(1)
      self.play(Write(t5))
      self.wait(2)
      self.remove(t3,t4,left,right,up,trix)
      self.play(t5.animate.shift(RIGHT*3.6,UP*2).scale(2),vgp.animate.scale(1.5))
      self.play(FadeOut(vgp))
      self.play(FadeOut(t5))
      self.play(FadeIn(sr))
      self.wait(1)
      self.remove(sr)
